services:
  api:
    build: .
    ports:
      - 1323:1323
    environment:
     - HOST=db
     - PORT=5432
     - USER=postgres
     - PASSWORD=postgres
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:16-alpine 
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports: 
      - "5432:5432"
    volumes:
      - ./fixture/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"
    volumes:
      - ./swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_FILE: /swagger.yaml