// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Customer API
 *
 * API for customer management
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type NewCustomer struct {

	Name string `json:"name,omitempty"`

	Address string `json:"address,omitempty"`

	Zip string `json:"zip,omitempty"`

	Phone string `json:"phone,omitempty"`

	Mktsegment string `json:"mktsegment,omitempty"`

	Nation string `json:"nation,omitempty"`

	Birthdate time.Time `json:"birthdate,omitempty"`
}

// AssertNewCustomerRequired checks if the required fields are not zero-ed
func AssertNewCustomerRequired(obj NewCustomer) error {
	return nil
}

// AssertNewCustomerConstraints checks if the values respects the defined constraints
func AssertNewCustomerConstraints(obj NewCustomer) error {
	return nil
}
